// fael — generated by `fael install`; rewritten on every install, edit fael instead.
// Maps OpenCode to the neutral hook protocol (docs/integrate.md): spawn
// `fael hook <event>`, Event JSON on stdin, Reply JSON on stdout. Never throws.
import { spawnSync } from "node:child_process";

const FAEL = __FAEL__;

function hook(event, e) {
  try {
    const r = spawnSync(FAEL, ["hook", event], {
      input: JSON.stringify({ ...e, client: "opencode" }),
      encoding: "utf-8",
      timeout: 5000,
    });
    return JSON.parse(r.stdout || "{}");
  } catch {
    return {};
  }
}

const EDIT = new Set(["edit", "write", "apply_patch"]);
const SEARCH = new Set(["grep", "glob", "bash"]);

// apply_patch (patchText) carries no filePath: read the paths off the patch
// headers, the same four claude.rs `patch_files` reads for Codex.
const PATCH_HEADERS = [
  "*** Add File: ",
  "*** Update File: ",
  "*** Delete File: ",
  "*** Move to: ",
];
function patch_files(patch) {
  if (typeof patch !== "string") return [];
  return patch
    .split("\n")
    .flatMap((l) => {
      const h = PATCH_HEADERS.find((h) => l.startsWith(h));
      return h ? [l.slice(h.length).trim()] : [];
    })
    .filter(Boolean);
}

export const Fael = async ({ client, directory }) => {
  // session start as RFC 3339 — the `session` string stop needs, and the same
  // string edit sends so both key one edit list
  const starts = new Map();
  const start = async (id) => {
    if (!starts.has(id)) {
      let t = Date.now();
      try {
        const s = await client.session.get({ path: { id } });
        t = s.data?.time?.created ?? t;
      } catch {}
      starts.set(id, new Date(t).toISOString());
    }
    return starts.get(id);
  };
  const briefs = new Map();
  const blocked = new Set();
  // the user line (Reply.notice) goes to a toast, never into the agent's
  // context; an OpenCode without the toast API simply shows nothing
  const say = (r) => {
    try {
      if (r.notice) client.tui?.showToast?.({ body: { message: r.notice, variant: "info" } })?.catch?.(() => {});
    } catch {}
  };

  return {
    // system is rebuilt per LLM call: fetch the brief once, push it every call
    "experimental.chat.system.transform": async (input, output) => {
      const id = input?.sessionID;
      if (!id) return;
      if (!briefs.has(id)) {
        const r = hook("session-start", { cwd: directory, session: await start(id) });
        say(r);
        briefs.set(id, r.context ?? "");
      }
      if (briefs.get(id)) output.system.push(briefs.get(id));
    },

    // bash tool env: OpenCode exports no session id to the shell, so hand
    // `fael add` its hook session (the same RFC 3339 `start(id)` string the
    // usage lines use) via FAEL_SESSION. PTY shells carry no sessionID — no-op.
    "shell.env": async (input, output) => {
      const id = input?.sessionID;
      if (!id) return;
      try {
        output.env ??= {};
        output.env.FAEL_SESSION = await start(id);
      } catch {}
    },

    "tool.execute.after": async (input, output) => {
      const session = await start(input.sessionID);
      if (SEARCH.has(input.tool)) {
        // grep/glob/bash reads push like a shell read: the raw call goes to
        // `fael hook search`, which resolves the touched files server-side
        const r = hook("search", {
          cwd: directory,
          session,
          tool: input.tool,
          tool_input: input.args ?? {},
          tool_response: output?.output ?? output ?? {},
        });
        if (r.context) output.output += `\n\n${r.context}`;
        say(r);
        return;
      }
      const event = input.tool === "read" ? "read" : EDIT.has(input.tool) ? "edit" : null;
      const files =
        input.tool === "apply_patch"
          ? patch_files(input.args?.patchText)
          : [input.args?.filePath].filter(Boolean);
      if (!event || files.length === 0) return;
      const r = hook(event, { cwd: directory, session, files });
      if (r.context) output.output += `\n\n${r.context}`;
      say(r);
    },

    // OpenCode has no Stop hook: on idle the last message goes to fael, which
    // files its `fael <kind>:` lines and, by default, never answers with a
    // block. Only the opt-in `[capture] block = true` mode does — that becomes
    // a prompt back. A non-blocking stop context has no mid-turn channel here —
    // prompting it would start a turn the user cannot cancel with Esc — so it
    // is dropped rather than re-prompted.
    event: async ({ event }) => {
      const id = event.properties?.sessionID;
      if (!id) return;
      // compaction dropped the pushed rows from context: `source: "compact"`
      // makes fael forget what it said there, so the next read tells them again
      if (event.type === "session.compacted") {
        const e = { cwd: directory, session: await start(id), source: "compact" };
        briefs.set(id, hook("session-start", e).context ?? "");
        return;
      }
      if (event.type !== "session.idle") return;
      let text = "";
      let reply = "";
      try {
        const m = await client.session.messages({ path: { id } });
        const asked = (m.data ?? []).filter((x) => x.info?.role === "assistant");
        const texts = (x) => (x?.parts ?? []).filter((p) => p.type === "text").map((p) => p.text);
        text = asked.flatMap(texts).join("\n");
        reply = texts(asked[asked.length - 1]).join("\n");
      } catch {}
      const r = hook("stop", {
        cwd: directory,
        session: await start(id),
        text,
        reply,
        stop_active: blocked.delete(id),
      });
      say(r);
      if (r.block && r.reason) {
        blocked.add(id);
        await client.session
          .prompt({ path: { id }, body: { parts: [{ type: "text", text: r.reason }] } })
          .catch(() => {});
      }
    },
  };
};
