// fael — generated by `fael install`; rewritten on every install, edit fael instead.
// Maps OpenCode to the neutral hook protocol (docs/integrate.md): spawn
// `fael hook <event>`, Event JSON on stdin, Reply JSON on stdout. Never throws.
import { spawnSync } from "node:child_process";

const FAEL = __FAEL__;

function hook(event, e) {
  try {
    const r = spawnSync(FAEL, ["hook", event], {
      input: JSON.stringify({ ...e, client: "opencode" }),
      encoding: "utf-8",
      timeout: 5000,
    });
    return JSON.parse(r.stdout || "{}");
  } catch {
    return {};
  }
}

const EDIT = new Set(["edit", "write", "multiedit"]);

export const Fael = async ({ client, directory }) => {
  // session start as RFC 3339 — the `session` string stop needs, and the same
  // string edit sends so both key one edit list
  const starts = new Map();
  const start = async (id) => {
    if (!starts.has(id)) {
      let t = Date.now();
      try {
        const s = await client.session.get({ path: { id } });
        t = s.data?.time?.created ?? t;
      } catch {}
      starts.set(id, new Date(t).toISOString());
    }
    return starts.get(id);
  };
  const briefs = new Map();
  const blocked = new Set();

  return {
    // system is rebuilt per LLM call: fetch the brief once, push it every call
    "experimental.chat.system.transform": async (input, output) => {
      const id = input?.sessionID;
      if (!id) return;
      if (!briefs.has(id)) {
        briefs.set(id, hook("session-start", { cwd: directory, session: await start(id) }).context ?? "");
      }
      if (briefs.get(id)) output.system.push(briefs.get(id));
    },

    // ponytail: filePath tools only — apply_patch (patchText) edits are not
    // recorded; stop then falls back to commits
    "tool.execute.after": async (input, output) => {
      const event = input.tool === "read" ? "read" : EDIT.has(input.tool) ? "edit" : null;
      const file = input.args?.filePath;
      if (!event || !file) return;
      const r = hook(event, { cwd: directory, session: await start(input.sessionID), files: [file] });
      if (r.context) output.output += `\n\n${r.context}`;
    },

    // OpenCode has no Stop hook: on idle the last message goes to fael, which
    // files its `fael <kind>:` lines and, by default, never answers with a
    // block. Only the opt-in `[capture] block = true` mode does — that becomes
    // a prompt back. A non-blocking stop context has no mid-turn channel here —
    // prompting it would start a turn the user cannot cancel with Esc — so it
    // is dropped rather than re-prompted.
    event: async ({ event }) => {
      const id = event.properties?.sessionID;
      if (!id) return;
      // compaction dropped the pushed rows from context: `source: "compact"`
      // makes fael forget what it said there, so the next read tells them again
      if (event.type === "session.compacted") {
        const e = { cwd: directory, session: await start(id), source: "compact" };
        briefs.set(id, hook("session-start", e).context ?? "");
        return;
      }
      if (event.type !== "session.idle") return;
      let text = "";
      let reply = "";
      try {
        const m = await client.session.messages({ path: { id } });
        const asked = (m.data ?? []).filter((x) => x.info?.role === "assistant");
        const texts = (x) => (x?.parts ?? []).filter((p) => p.type === "text").map((p) => p.text);
        text = asked.flatMap(texts).join("\n");
        reply = texts(asked[asked.length - 1]).join("\n");
      } catch {}
      const r = hook("stop", {
        cwd: directory,
        session: await start(id),
        text,
        reply,
        stop_active: blocked.delete(id),
      });
      if (r.block && r.reason) {
        blocked.add(id);
        await client.session
          .prompt({ path: { id }, body: { parts: [{ type: "text", text: r.reason }] } })
          .catch(() => {});
      }
    },
  };
};
